name: Release Svelte

on:
  push:
    tags:
      - "svelte-v*.*.*"

permissions:
  contents: write

jobs:
  release:
    if: contains(github.ref, "refs/tags/svelte-v")
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          clean: true

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"

      - run: npm ci

      - run: npm run build -w @fefade-ui/svelte

      - run: cp README.md packages/svelte

      - run: npm publish -w @fefade-ui/svelte
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
